# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#max_width
max_width = 120

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#comment_width
# Nightly only 4 now
# comment_width = 80

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#doc_comment_code_block_width
# Nightly only 4 now
# doc_comment_code_block_width = 80

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#match_block_trailing_comma
match_block_trailing_comma = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#wrap_comments
# Nightly only 4 now
# wrap_comments = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#edition
edition = "2021"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#error_on_line_overflow
# Nightly only 4 now
# error_on_line_overflow = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#version
# Nightly only 4 now
# version = "Two"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#tab_spaces
tab_spaces = 2

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#use_field_init_shorthand
use_field_init_shorthand = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#where_single_line
# Nightly only 4 now
# where_single_line = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#binop_separator
# Nightly only 4 now
# binop_separator = "Back"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#brace_style
# Nightly only 4 now
# brace_style = "PreferSameLine"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#color
# Nightly only 4 now
# color = "Always"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#combine_control_expr
# Nightly only 4 now
# combine_control_expr = false

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#condense_wildcard_suffixes
# Nightly only 4 now
# condense_wildcard_suffixes = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#fn_single_line
# Nightly only 4 now
# fn_single_line = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#force_multiline_blocks
# Nightly only 4 now
# force_multiline_blocks = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_code_in_doc_comments
# Nightly only 4 now
# format_code_in_doc_comments = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#format_strings
# Nightly only 4 now
# format_strings = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_indent
# Nightly only 4 now
# imports_indent = "Visual"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#indent_style
# Nightly only 4 now
# indent_style = "Visual"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#match_arm_leading_pipes
match_arm_leading_pipes = "Always"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#merge_derives
# TODO: check if this helps or not
merge_derives = false

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity
# Nightly only 4 now
# imports_granularity = "Crate"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#normalize_comments
# Nightly only 4 now
# normalize_comments = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#normalize_doc_attributes
# Nightly only 4 now
# normalize_doc_attributes = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#overflow_delimited_expr
# Nightly only 4 now
# overflow_delimited_expr = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#remove_nested_parens
remove_nested_parens = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#reorder_impl_items
# Nightly only 4 now
# reorder_impl_items = true

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#group_imports
# Nightly only 4 now
# group_imports = "One"

# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#trailing_semicolon
# Nightly only 4 now
# trailing_semicolon = false
